name: xmp
description: XMP module helps to extract xmp data from images.
version: 1.0.2
homepage: https://github.com/justkawal/xmp

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  xml: ^6.3.0 #^4.5.1
  utility: ^1.0.3 #^1.0.1

#dev_dependencies:
